style = "default"

indent = 4
margin = 120

always_for_in = true

short_to_long_function_def = true
long_to_short_function_def = false
force_long_function_def = false
always_use_return = true

remove_extra_newlines = false

align_assignment = true
align_struct_field = true
align_pair_arrow = true
align_conditional = true

disallow_single_arg_nesting = false

trailing_comma = false
trailing_zero = true

whitespace_in_kwargs = true #
whitespace_typedefs = false
whitespace_ops_in_indices = true #
separate_kwargs_with_semicolon = false
surround_whereop_typeparameters = false

import_to_using = false
pipe_to_function_call = false

format_docstrings = false

join_lines_based_on_source = true

indent_submodule = false
short_circuit_to_if = false

format_markdown = false

normalize_line_endings = "unix"

ignore = []
