# Copyright (C) 2023 Luigi Pertoldi <gipert@pm.me>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import annotations

import logging
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path

import dbetto
from dbetto import AttrsDict
from legendmeta.police import validate_dict_schema

from . import SimflowConfig, patterns
from .exceptions import SimflowConfigError
from .metadata import (
    encode_psd_usability,
    get_par_settings,
    get_runlist,
    get_simconfig,
    get_tier_settings,
    runinfo,
    simpars,
)

log = logging.getLogger(__name__)

STEPS_ORDERED: list[str] = ["vtx", "stp", "par", "opt", "hit", "evt", "cvt", "pdf"]


def get_simid_njobs(config: SimflowConfig, simid: str) -> int:
    """Number of jobs that will be generated for a `tier.simid`.

    Based on the information contained in the `stp` tiers simulation
    configuration. If ``config.benchmark`` is true, this function always
    returns 1.
    """
    if "benchmark" in config and config.benchmark.get("enabled", False):
        return 1

    sconfig = get_simconfig(config, "stp", simid=simid)

    if "number_of_jobs" in sconfig:
        return sconfig.number_of_jobs
    return get_simconfig(config, "stp", simid=simid, field="number_of_jobs")


def gen_list_of_simid_inputs(
    config: SimflowConfig, tier: str, simid: str
) -> list[Path]:
    """Generate the list of input files for a `tier.simid`."""
    n_jobs = get_simid_njobs(config, simid)
    return patterns.input_simid_filenames(config, n_jobs, tier=tier, simid=simid)


def gen_list_of_simid_outputs(
    config: SimflowConfig, tier: str, simid: str, max_files: int | None = None
) -> list[Path]:
    """Generate the list of output files for a `tier.simid`."""
    n_jobs = get_simid_njobs(config, simid)
    if max_files is not None:
        n_jobs = min(n_jobs, max_files)
    return patterns.output_simid_filenames(config, n_jobs, tier=tier, simid=simid)


def gen_list_of_plots_outputs(config: SimflowConfig, tier: str, simid: str):
    """Generate the list of plots files for a `tier.simid`."""
    if tier == "cvt":
        return [
            patterns.plot_tier_cvt_observables_filename(config, simid=simid),
        ]
    if tier == "hit":
        return [
            patterns.plot_tier_hit_observables_filename(config, simid=simid),
        ]
    if tier == "opt":
        return [
            patterns.plot_tier_opt_observables_filename(config, simid=simid),
        ]
    if tier == "stp":
        # geometry validation plots, a byproduct of the stp geometry build
        return [
            patterns.plot_tier_stp_vertices_filename(config, simid=simid),
            patterns.plot_geom_rendering_filename(config, simid=simid),
            patterns.plot_geom_hpge_mass_filename(config, simid=simid),
        ]
    if tier == "par":
        # HPGe drift-time map plots, a byproduct of the par step; only produced
        # when PSD is simulated in the hit tier
        if not get_tier_settings(config, "hit").get("simulate_psd", True):
            return []
        files = gen_list_of_dtmap_plots_outputs(config, simid)
        if get_tier_settings(config, "hit").get("simulate_psd_with_psl", True):
            files.extend(
                gen_list_of_superpulses_uniformity_plots_outputs(config, simid)
            )
        return files
    return []


# simid independent stuff


def gen_list_of_all_simids(config: SimflowConfig) -> list[str]:
    r"""Generate a list of all `simid`\ s defined in the simflow.

    The list is generated by querying the ``stp`` tier configuration.
    """
    return get_simconfig(config, "stp").keys()


def gen_list_of_all_simid_outputs(config: SimflowConfig, tier: str) -> list[Path]:
    r"""Generate a list of all files that belong to a `tier`."""
    mlist = []
    slist = gen_list_of_all_simids(config)
    for simid in slist:
        mlist += gen_list_of_simid_outputs(config, tier, simid)

    return mlist


def gen_list_of_all_plots_outputs(config: SimflowConfig, tier: str) -> list[Path]:
    r"""Generate a list of all plot files that belong to a `tier`."""
    mlist = []
    for simid in gen_list_of_all_simids(config):
        mlist += gen_list_of_plots_outputs(config, tier, simid)

    return mlist


def gen_list_of_all_plots(config: SimflowConfig) -> list[Path]:
    r"""Generate a list of all plot files across all active `make_steps`.

    Iterates over :func:`gen_list_of_all_plots_outputs` for every tier in
    ``config.make_steps``.
    """
    files = []
    for tier in config.make_steps:
        files.extend(gen_list_of_all_plots_outputs(config, tier))
    return files


def crystal_meta(config: SimflowConfig, diode_meta: AttrsDict) -> AttrsDict:
    """Get the crystal metadata starting from the diode metadata."""
    ids = {"bege": "B", "coax": "C", "ppc": "P", "icpc": "V"}
    crystal_name = (
        ids[diode_meta.type]
        + format(diode_meta.production.order, "02d")
        + diode_meta.production.crystal
    )
    crystal_db = config.metadata.hardware.detectors.germanium.crystals
    if crystal_name in crystal_db:
        return crystal_db[crystal_name]
    return None


def start_key(config: SimflowConfig, runid: str) -> str:
    """Get the start key for a runid."""
    _, period, run, datatype = runid.split("-")
    return config.metadata.datasets.runinfo[period][run][datatype].start_key


def pivot_detinfo(
    nested: Mapping[str, Mapping[str, Mapping[str, object]]],
) -> dict[str, dict[str, dict[str, object]]]:
    """Pivot ``{runid: {det: {flag: value}}}`` into ``{flag: {runid: {det: value}}}``.

    Used to lay out the per-detector information as one ``detinfo`` file per
    flag (see :func:`legendsimflow.patterns.detinfo_filename`). Flags absent
    from an entry (e.g. non-geds detectors carry only ``usability``) simply do
    not contribute to the corresponding flag mapping.
    """
    out: dict[str, dict[str, dict[str, object]]] = {}
    for runid, dets in nested.items():
        for det, entry in dets.items():
            for flag, value in entry.items():
                out.setdefault(flag, {}).setdefault(runid, {})[det] = value
    return out


def _hpge_is_modelable(
    config: SimflowConfig,
    name: str,
    usability: str,
    skip: Mapping[str, str],
    operational_voltage: int | None,
    min_voltage_above_depletion: int,
) -> bool:
    """Whether the HPGe `name` is valid for drift-time-map modeling.

    See :func:`gen_hpge_modeling_status` for the criteria.
    """
    # we don't model detectors that are OFF or AC because we need to tune the
    # models to valid L200 data
    if usability != "on":
        return False

    # explicitly excluded via the validity-based skip metadata
    if name in skip:
        return False

    # detectors not operated far enough above their depletion voltage are not
    # modeled (off detectors have no operational voltage)
    if operational_voltage is None:
        return False

    # detectors without a depletion voltage in the metadata are not modeled
    try:
        diode = config.metadata.hardware.detectors.germanium.diodes[name]
        depletion_voltage = diode.characterization.l200_site.depletion_voltage_in_V
    except (KeyError, AttributeError, FileNotFoundError):
        return False

    if depletion_voltage is None:
        return False

    if operational_voltage < depletion_voltage + min_voltage_above_depletion:
        return False

    # detectors without an impurity curve in the crystal metadata cannot be
    # modeled
    m = crystal_meta(config, diode)
    return bool(
        m is not None
        and validate_dict_schema(
            m,
            {"impurity_curve": {"parameters": None}},
            greedy=False,
            typecheck=False,
            verbose=False,
        )
    )


def gen_hpge_modeling_status(
    config: SimflowConfig, runid: str
) -> dict[str, dict[str, bool | int | None]]:
    """Assess every HPGe deployed in `runid` for drift-time-map modeling.

    Iterates over the germanium detectors deployed in `runid` (via the LEGEND
    channelmap) and records, for each, whether it is valid for modeling along
    with the quantities needed downstream. Returns a mapping

    .. code-block::

        {
          'V00048A': {
            'is_modelable': True,
            'operational_voltage_in_V': 4200,
          },
          ...
        }

    A detector ``is_modelable`` when all of the following hold: it is ``ON``
    (i.e. not OFF or AC), it is not listed in the validity-based skip metadata
    ``simprod/config/pars/{experiment}/geds/skip/`` for `runid`, it is operated
    at least ``min_voltage_above_depletion_in_V`` (default 100 V, configurable
    via the ``modeling`` par settings) above its depletion voltage
    (``characterization.l200_site.depletion_voltage_in_V`` in the diode
    metadata), and its crystal metadata provides an impurity curve.
    ``operational_voltage_in_V`` is ``None`` for detectors with no operational
    voltage (e.g. off detectors).

    Warning
    -------
    This function is expensive in terms of filesystem I/O! Do not call it
    multiple times or in hot loops.
    """
    timestamp = start_key(config, runid)
    metadata = config.metadata
    chmap = metadata.channelmap(timestamp, skip_version_check=True)

    skip = simpars(metadata, "geds.skip", runid, config.experiment, default={})

    # minimum operational-voltage margin above depletion required to consider an
    # HPGe modelable; overridable per experiment via the modeling par settings
    min_voltage_above_depletion = get_par_settings(config, "modeling").get(
        "min_voltage_above_depletion_in_V", 100
    )

    status = {}
    for _, hpge in chmap.group("system").geds.items():
        name = hpge.name

        # off detectors (and others without a bias) have no operational voltage
        try:
            operational_voltage = get_hpge_voltage(config, name, runid)
        except KeyError:
            operational_voltage = None

        status[name] = {
            "is_modelable": _hpge_is_modelable(
                config,
                name,
                chmap[name].analysis.usability,
                skip,
                operational_voltage,
                min_voltage_above_depletion,
            ),
            "operational_voltage_in_V": operational_voltage,
        }

    return status


def gen_list_of_hpges_valid_for_modeling(
    config: SimflowConfig, runid: str
) -> list[str]:
    """Make a sorted list of HPGe detectors for which we want to compute a model.

    Convenience wrapper over :func:`gen_hpge_modeling_status` returning the
    sorted names of the detectors that are valid for modeling in `runid` (see
    that function for the criteria).

    Warning
    -------
    This function is expensive in terms of filesystem I/O! Do not call it
    multiple times or in hot loops.
    """
    status = gen_hpge_modeling_status(config, runid)
    hpges = sorted(name for name, entry in status.items() if entry["is_modelable"])

    if len(hpges) == 0:
        msg = f"the list of HPGes valid for drift-time map generation in {runid} is empty!"
        log.warning(msg)

    return hpges


def gen_list_of_all_hpges_valid_for_modeling(
    config: SimflowConfig,
) -> dict[str, dict[str, dict[str, bool | int | None]]]:
    """Generate the modeling status of every HPGe detector, for every runid.

    Assesses all deployed HPGe detectors for each runid via
    :func:`gen_hpge_modeling_status`. Returns the following dictionary:

    .. code-block::

        {
          'l200-p03-r000-phy': {
            'V00048A': {'is_modelable': True, 'operational_voltage_in_V': 4200},
            ...
          },
          ...
        }

    i.e. a mapping ``runid -> hpge -> {"is_modelable": flag,
    "operational_voltage_in_V": voltage}`` covering both modelable and
    non-modelable detectors. Filter on ``is_modelable`` to recover the
    detectors valid for modeling.
    """
    all_runids = set()
    for simid in gen_list_of_all_simids(config):
        all_runids.update(get_runlist(config, simid))

    return {
        runid: gen_hpge_modeling_status(config, runid) for runid in sorted(all_runids)
    }


def gen_list_of_all_usabilities(
    config: SimflowConfig,
) -> AttrsDict[str, AttrsDict[str, dict]]:
    """Generate a usability mapping for all detectors and all runs defined in the Simflow.

    Use this function to build a cache to avoid repeated metadata lookups.
    Returns the following dictionary:

    .. code-block::

        {
          'l200-p03-r000-phy': {
            'V00048A': {
              'usability': 'on',
              'psd_usability': 'valid',
              'crystal_metadata_usability': 'valid',
            },
            ...
          },
          ...
        }

    ``psd_usability`` is the ``psd.status.low_aoe`` field in the channel map
    status for germanium detectors (encoded later via
    ``legendsimflow.metadata.PSD_USABILITY_CODE``). If the field is absent it
    defaults silently to ``"valid"``; if it has an unexpected value a warning
    is emitted and it also defaults to ``"valid"``.

    ``crystal_metadata_usability`` is the crystal metadata usability for
    germanium detectors (see :func:`get_hpge_crystal_metadata_usability`); it is
    ``None`` when the information is not available in the metadata.

    Parameters
    ----------
    config
        Simflow configuration object.

    """
    all_runids = set()
    for simid in gen_list_of_all_simids(config):
        all_runids.update(get_runlist(config, simid))

    out_dict = {}
    for runid in all_runids:
        out_dict[runid] = {}
        rinfo = runinfo(config.metadata, runid)
        chmap = config.metadata.channelmap(rinfo.start_key, skip_version_check=True)
        for chname in chmap:
            if "analysis" in chmap[chname]:
                usability = chmap[chname].analysis.usability

                entry = {"usability": usability}
                if chmap[chname].system == "geds":
                    psd_usability = "valid"
                    try:
                        psd_status = chmap[chname].analysis.psd.status.low_aoe
                        try:
                            encode_psd_usability(psd_status)  # validate
                            psd_usability = psd_status
                        except KeyError:
                            msg = f"unexpected psd.status.low_aoe value {psd_status!r} for {chname} in {runid}, defaulting to valid"
                            log.warning(msg)
                    except AttributeError:
                        pass
                    entry["psd_usability"] = psd_usability
                    entry["crystal_metadata_usability"] = (
                        get_hpge_crystal_metadata_usability(config, chname)
                    )

                out_dict[runid][chname] = entry

    return AttrsDict(out_dict)


def gen_list_of_all_runids(config) -> set[str]:
    """The full list of runids required in the Simflow."""
    return {
        runid
        for simid in gen_list_of_all_simids(config)
        for runid in get_runlist(config, simid)
    }


def get_hpge_voltage(config: SimflowConfig, hpge: str, runid: str) -> int:
    """Get the operational voltage for an HPGe in a given run.

    Returns the voltage as an integer.
    """
    try:
        opv = simpars(config.metadata, "geds.opv", runid, config.experiment)[
            hpge
        ].operational_voltage_in_V
    except KeyError as e:
        msg = f"operational voltage for hpge {hpge} not found in run {runid}"
        raise KeyError(msg) from e
    return int(opv)


def get_hpge_crystal_metadata_usability(config: SimflowConfig, hpge: str) -> str | None:
    """Get the crystal metadata usability for an HPGe detector.

    Reads ``hardware.detectors.germanium.crystals[...].slices[...].status`` for
    the slice the detector was cut from. Returns ``None`` if the information is
    not available in the metadata.
    """
    try:
        diode = config.metadata.hardware.detectors.germanium.diodes[hpge]
        crystal = crystal_meta(config, diode)
        if crystal is None:
            return None
        return crystal.slices[diode.production.slice].status
    except (KeyError, AttributeError, FileNotFoundError):
        return None


def gen_list_of_dtmaps(
    config: SimflowConfig,
    runid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of HPGe drift-time map files for a `runid`."""
    if cache is None:
        hpges = gen_list_of_hpges_valid_for_modeling(config, runid)
        return [
            patterns.output_dtmap_filename(
                config,
                hpge_detector=hpge,
                hpge_voltage=get_hpge_voltage(config, hpge, runid),
            )
            for hpge in hpges
        ]
    # use the cache to avoid calling get_hpge_voltage()
    hpge_voltages = cache[runid]
    return [
        patterns.output_dtmap_filename(
            config,
            hpge_detector=hpge,
            hpge_voltage=entry["operational_voltage_in_V"],
        )
        for hpge, entry in hpge_voltages.items()
    ]


def gen_list_of_dtmap_info_files(
    config: SimflowConfig,
    cache: Mapping[str, Mapping[str, Mapping[str, int]]],
) -> list[Path]:
    """Deduplicated list of HPGe SSD-modeling info sidecars for the modeling `cache`."""
    seen: dict[str, Path] = {}
    for dets in cache.values():
        for hpge, entry in dets.items():
            path = patterns.output_dtmap_info_filename(
                config,
                hpge_detector=hpge,
                hpge_voltage=entry["operational_voltage_in_V"],
            )
            seen[str(path)] = path
    return list(seen.values())


def collect_hpge_ssd_modeling_info(
    config: SimflowConfig,
    cache: Mapping[str, Mapping[str, Mapping[str, int]]],
) -> dict[str, dict[str, dict[str, object]]]:
    """Aggregate the HPGe SSD-modeling sidecars into a ``runid -> detector -> {scalars}`` mapping."""
    # a single sidecar is shared by every runid operating a detector at the same
    # voltage, so cache each file's contents to read it from disk only once
    loaded: dict[str, dict[str, object]] = {}
    out: dict[str, dict[str, dict[str, object]]] = {}
    for runid, dets in cache.items():
        for hpge, entry in dets.items():
            path = patterns.output_dtmap_info_filename(
                config,
                hpge_detector=hpge,
                hpge_voltage=entry["operational_voltage_in_V"],
            )
            key = str(path)
            if key not in loaded:
                loaded[key] = dict(dbetto.utils.load_dict(path))
            out.setdefault(runid, {})[hpge] = dict(loaded[key])
    return out


def gen_list_of_merged_dtmaps(
    config: SimflowConfig, simid: str, has_psd=True
) -> list[Path]:
    r"""Generate the list of (merged) HPGe drift-time map files for all requested `runid`\ s."""
    if not has_psd:
        return []

    return [
        patterns.output_dtmap_merged_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_ideal_psls(
    config: SimflowConfig,
    runid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of ideal HPGe pulse-shape library files for a `runid`.

    If ``cache`` is provided, it must be the modelable-HPGe cache produced by
    :func:`gen_list_of_all_hpges_valid_for_modeling` and avoids repeated
    metadata lookups.
    """
    if cache is None:
        hpges = gen_list_of_hpges_valid_for_modeling(config, runid)
        return [
            patterns.output_ideal_psl_filename(
                config,
                hpge_detector=hpge,
                hpge_voltage=get_hpge_voltage(config, hpge, runid),
            )
            for hpge in hpges
        ]
    # use the cache to avoid calling get_hpge_voltage()
    hpge_voltages = cache[runid]
    return [
        patterns.output_ideal_psl_filename(
            config,
            hpge_detector=hpge,
            hpge_voltage=entry["operational_voltage_in_V"],
        )
        for hpge, entry in hpge_voltages.items()
    ]


def gen_list_of_realistic_psls(
    config: SimflowConfig,
    runid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
    simulate_psd_with_psl: bool = True,
) -> list[Path]:
    """Generate the list of realistic HPGe pulse-shape library files for a `runid`.

    If ``cache`` is provided, it must be the modelable-HPGe cache produced by
    :func:`gen_list_of_all_hpges_valid_for_modeling` and avoids repeated
    metadata lookups.
    """
    files = []
    if not simulate_psd_with_psl:
        return []

    hpges = (
        gen_list_of_hpges_valid_for_modeling(config, runid)
        if cache is None
        else cache[runid].keys()
    )
    for hpge in hpges:
        files.append(
            patterns.output_realistic_psl_filename(
                config, runid=runid, hpge_detector=hpge
            )
        )

    return files


def gen_list_of_merged_realistic_psls(
    config: SimflowConfig, simid: str, simulate_psd_with_psl: bool = True
) -> list[Path]:
    r"""Generate the list of (merged) HPGe PSL files for all requested `runid`\ s."""
    if not simulate_psd_with_psl:
        return []

    return [
        patterns.output_realistic_psl_merged_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_dtmap_plots_outputs(
    config: SimflowConfig,
    simid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of HPGe drift-time map plot outputs."""
    files = set()
    for runid in get_runlist(config, simid):
        if cache is None:
            hpges = gen_list_of_hpges_valid_for_modeling(config, runid)
            for hpge in hpges:
                files.add(
                    patterns.plot_dtmap_filename(
                        config,
                        hpge_detector=hpge,
                        hpge_voltage=get_hpge_voltage(config, hpge, runid),
                    )
                )
        else:
            # use the cache to avoid calling get_hpge_voltage()
            for hpge, entry in cache[runid].items():
                files.add(
                    patterns.plot_dtmap_filename(
                        config,
                        hpge_detector=hpge,
                        hpge_voltage=entry["operational_voltage_in_V"],
                    )
                )
    return list(files)


def gen_list_of_currmods(
    config: SimflowConfig,
    runid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of HPGe current model parameter files for a `runid`."""
    hpges = (
        gen_list_of_hpges_valid_for_modeling(config, runid)
        if cache is None
        else cache[runid].keys()
    )
    return [
        patterns.output_currmod_filename(config, hpge_detector=hpge, runid=runid)
        for hpge in hpges
    ]


def gen_list_of_merged_currmods(
    config: SimflowConfig, simid: str, has_psd: bool = True
) -> list[Path]:
    r"""Generate the list of (merged) HPGe current model parameter files for all requested `runid`\ s."""
    if not has_psd:
        return []

    return [
        patterns.output_currmod_merged_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_elecmods(
    config: SimflowConfig,
    runid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of HPGe electronics model parameter files for a `runid`."""
    hpges = (
        gen_list_of_hpges_valid_for_modeling(config, runid)
        if cache is None
        else cache[runid].keys()
    )
    return [
        patterns.output_elecmod_filename(config, hpge_detector=hpge, runid=runid)
        for hpge in hpges
    ]


def gen_list_of_merged_elecmods(config: SimflowConfig, simid: str) -> list[Path]:
    r"""Generate the list of HPGe electronics model parameter files for all requested `runid`\ s."""
    return [
        patterns.output_elecmod_merged_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_currmod_plots_outputs(
    config: SimflowConfig,
    simid: str,
    cache: dict[str, dict[str, dict[str, int]]] | None = None,
) -> list[Path]:
    """Generate the list of HPGe current-pulse model plot outputs."""
    files = []
    for runid in get_runlist(config, simid):
        hpges = (
            gen_list_of_hpges_valid_for_modeling(config, runid)
            if cache is None
            else cache[runid].keys()
        )
        for hpge in hpges:
            files.append(
                patterns.plot_currmod_filename(config, hpge_detector=hpge, runid=runid)
            )

    return files


def gen_list_of_superpulses_uniformity_plots_outputs(
    config: SimflowConfig, simid: str, cache: dict[str, dict[str, int]] | None = None
) -> list[Path]:
    """Generate the list of superpulse response uniformity plot outputs."""
    files = []
    for runid in get_runlist(config, simid):
        hpges = (
            gen_list_of_hpges_valid_for_modeling(config, runid)
            if cache is None
            else cache[runid].keys()
        )
        for hpge in hpges:
            files.append(
                patterns.plot_superpulses_uniformity_filename(
                    config, build_per_runid=True, hpge_detector=hpge, runid=runid
                )
            )
    return files


def gen_list_of_eresmods(config: SimflowConfig, simid: str) -> list[Path]:
    r"""Generate the list of HPGe energy resolution model parameter files for all requested `runid`\ s."""
    return [
        patterns.output_eresmod_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_aoeresmods(config: SimflowConfig, simid: str) -> list[Path]:
    r"""Generate the list of HPGe A/E resolution model parameter files for all requested `runid`\ s."""
    return [
        patterns.output_aoeresmod_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_psdcuts(config: SimflowConfig, simid: str) -> list[Path]:
    r"""Generate the list of HPGe PSD cut value files for all requested `runid`\ s."""
    return [
        patterns.output_psdcuts_filename(config, runid=runid)
        for runid in get_runlist(config, simid)
    ]


def gen_list_of_all_par_outputs(config: SimflowConfig) -> list[Path]:
    """Generate the list of all (non-plot) ``par`` step output files in the Simflow."""
    files: list[Path] = [
        patterns.detinfo_filename(config, flag)
        for flag in (
            "usability",
            "psd_usability",
            "crystal_metadata_usability",
            "is_modelable",
            "operational_voltage_in_V",
        )
    ]
    for simid in gen_list_of_all_simids(config):
        files.append(patterns.simstat_part_filename(config, simid=simid))
        files.extend(gen_list_of_eresmods(config, simid))
        files.extend(gen_list_of_aoeresmods(config, simid))
        files.extend(gen_list_of_psdcuts(config, simid))
    return files


# tier cvt
def gen_list_of_all_tier_cvt_outputs(config: SimflowConfig, **kwargs) -> list[Path]:
    """Generate the list of all ``cvt`` tier files in the Simflow."""
    return [
        patterns.output_tier_cvt_filename(config, simid=simid, **kwargs)
        for simid in gen_list_of_all_simids(config)
    ]


# tier pdf
def gen_list_of_all_tier_pdf_outputs(config: SimflowConfig, **kwargs) -> list[Path]:
    """Generate the list of all ``pdf`` tier files in the Simflow."""
    return [
        patterns.output_tier_pdf_filename(config, simid=simid, **kwargs)
        for simid in gen_list_of_all_simids(config)
    ]


def process_simlist(
    config: SimflowConfig,
    simlist: Iterable[str] | None = None,
    make_steps: Sequence[str] | None = None,
) -> list[Path]:
    """Produce a list of all output files that refer to a `simlist`.

    Each simlist item is ``<tier>.<simid>``. The tier is interpreted as the
    *latest* tier requested for that simid; outputs are produced cumulatively
    for all tiers up to (and including) that tier in `make_steps`.
    """
    if simlist is None:
        simlist = config.simlist
    if make_steps is None:
        make_steps = STEPS_ORDERED

    # if it's a list, every item is a simid
    # otherwise, interpret as comma-separated list
    if not isinstance(simlist, list):
        simlist = simlist.split(",")

    mlist: list[Path] = []
    for line in simlist:
        parts = line.split(".")
        if len(parts) != 2:
            msg = (
                "simflow-config.simlist",
                f"item '{line}' is not in the format <tier>.<simid>",
            )
            raise SimflowConfigError(*msg)

        tier = parts[0].strip()
        simid = parts[1].strip()

        if tier not in make_steps:
            msg = (
                "simflow-config.simlist",
                f"unknown step or missing from 'make_steps': {tier!r}",
            )
            raise SimflowConfigError(*msg)

        _non_simid_steps = {"vtx", "par"}
        if tier in _non_simid_steps:
            msg = (
                "simflow-config.simlist",
                f"step {tier!r} does not produce simid-scoped outputs and cannot be used in the simlist",
            )
            raise SimflowConfigError(*msg)

        # cumulative: build all tiers up to the requested one
        for t in make_steps[: make_steps.index(tier) + 1]:
            mlist += gen_list_of_plots_outputs(config, t, simid)

            if t in ("vtx", "par"):
                pass
            elif t in ("stp", "opt", "hit", "evt"):
                mlist += gen_list_of_simid_outputs(config, t, simid)
            elif t == "cvt":
                mlist.append(patterns.output_tier_cvt_filename(config, simid=simid))
            elif t == "pdf":
                mlist.append(patterns.output_tier_pdf_filename(config, simid=simid))

    return mlist
