---
title: DAG
---
flowchart TB
	id0[plot_tier_stp_vertices]
	id1[build_tier_stp]
	id2[build_geom_gdml]
	id3[gen_geom_config]
	id4[gen_remage_macro]
	id5[plot_geom_rendering]
	id6[plot_geom_hpge_mass]
	id7[build_tier_vtx]
	id8[cache_detector_usabilities]
	id9[cache_modelable_hpges]
	id10[make_simstat_partition_file]
	id11[extract_hpge_observables_models]
	id12[simulate_electron_gun]
	id13[build_tier_opt]
	id14[plot_tier_opt_observables]
	id15[build_tier_hit]
	id16[plot_tier_hit_observables]
	id17[build_tier_evt]
	id18[build_tier_cvt]
	id19[plot_tier_cvt_observables]
	id20[build_tier_pdf]
	id21[merge_hpge_drift_time_maps]
	id22[build_hpge_drift_time_map]
	id23[_init_julia_env]
	id24[merge_current_pulse_model_pars]
	id25[extract_current_pulse_model]
	id26[extract_hpge_aoemean_energy_dependence]
	id27[aggregate_hpge_ssd_modeling_info]
	id28[all]
	id29[plot_hpge_drift_time_maps]
	style id0 fill:#5783D9,stroke-width:2px,color:#333333
	style id1 fill:#C0D957,stroke-width:2px,color:#333333
	style id2 fill:#D98E57,stroke-width:2px,color:#333333
	style id3 fill:#57D99F,stroke-width:2px,color:#333333
	style id4 fill:#57D9AA,stroke-width:2px,color:#333333
	style id5 fill:#57BAD9,stroke-width:2px,color:#333333
	style id6 fill:#57C5D9,stroke-width:2px,color:#333333
	style id7 fill:#B5D957,stroke-width:2px,color:#333333
	style id8 fill:#AAD957,stroke-width:2px,color:#333333
	style id9 fill:#9FD957,stroke-width:2px,color:#333333
	style id10 fill:#57D9B5,stroke-width:2px,color:#333333
	style id11 fill:#67D957,stroke-width:2px,color:#333333
	style id12 fill:#5762D9,stroke-width:2px,color:#333333
	style id13 fill:#D6D957,stroke-width:2px,color:#333333
	style id14 fill:#578ED9,stroke-width:2px,color:#333333
	style id15 fill:#D9D057,stroke-width:2px,color:#333333
	style id16 fill:#5799D9,stroke-width:2px,color:#333333
	style id17 fill:#D9C557,stroke-width:2px,color:#333333
	style id18 fill:#D9BA57,stroke-width:2px,color:#333333
	style id19 fill:#57A4D9,stroke-width:2px,color:#333333
	style id20 fill:#CBD957,stroke-width:2px,color:#333333
	style id21 fill:#57D9D6,stroke-width:2px,color:#333333
	style id22 fill:#D99957,stroke-width:2px,color:#333333
	style id23 fill:#D95757,stroke-width:2px,color:#333333
	style id24 fill:#57D9C0,stroke-width:2px,color:#333333
	style id25 fill:#89D957,stroke-width:2px,color:#333333
	style id26 fill:#72D957,stroke-width:2px,color:#333333
	style id27 fill:#D96257,stroke-width:2px,color:#333333
	style id28 fill:#D96D57,stroke-width:2px,color:#333333
	style id29 fill:#57AFD9,stroke-width:2px,color:#333333
	id1 --> id0
	id7 --> id1
	id4 --> id1
	id2 --> id1
	id3 --> id2
	id2 --> id4
	id3 --> id5
	id3 --> id6
	id2 --> id7
	id1 --> id10
	id10 --> id13
	id1 --> id13
	id8 --> id13
	id2 --> id13
	id13 --> id14
	id21 --> id15
	id11 --> id15
	id24 --> id15
	id2 --> id15
	id1 --> id15
	id8 --> id15
	id26 --> id15
	id10 --> id15
	id15 --> id16
	id1 --> id17
	id15 --> id17
	id13 --> id17
	id8 --> id17
	id10 --> id17
	id17 --> id18
	id18 --> id19
	id18 --> id20
	id22 --> id21
	id23 --> id22
	id25 --> id24
	id12 --> id26
	id9 --> id26
	id21 --> id26
	id24 --> id26
	id22 --> id27
	id15 --> id28
	id18 --> id28
	id25 --> id28
	id29 --> id28
	id10 --> id28
	id16 --> id28
	id5 --> id28
	id27 --> id28
	id14 --> id28
	id0 --> id28
	id19 --> id28
	id11 --> id28
	id1 --> id28
	id9 --> id28
	id13 --> id28
	id6 --> id28
	id17 --> id28
	id8 --> id28
	id26 --> id28
	id20 --> id28
	id22 --> id29
