# reserved first-level fields:
#   - metadata

experiment: l200cfg09

# simflow_rng_seed: 0

# runlist:
# - l200-p03-r000-phy
# - l200-p03-r001-phy
# - l200-p03-r002-phy
# - l200-p03-r005-phy
# - l200-p04-r000-phy
# - l200-p04-r001-phy

simlist: all

make_tiers:
  - vtx
  - stp
  - opt
  - hit
  - evt
  - cvt

# legend_metadata_version: main

benchmark:
  enabled: false
  n_primaries:
    stp: 10_000

paths:
  l200data: <...>/public/prodenv/prod-blind/ref-v1.0.0
  benchmarks: $_/generated/benchmarks
  log: $_/generated/log

  metadata: $_/inputs
  config: $_/inputs/simprod/config
  optical_maps:
    fiber: $_/inputs/simprod/l200a-optical-map-fiber.lh5
    lar: $_/inputs/simprod/l200a-optical-map-lar.lh5
    pen: $_/inputs/simprod/l200a-optical-map-pen.lh5

  genmeta: $_/generated/metadata
  macros: $_/generated/macros
  geom: $_/generated/geom
  dtmaps: $_/generated/hpge/dtmaps
  tier_vtx: $_/generated/tier/vtx
  tier_stp: $_/generated/tier/stp
  tier_opt: $_/generated/tier/opt
  tier_hit: $_/generated/tier/hit
  tier_evt: $_/generated/tier/evt
  tier_cvt: $_/generated/tier/cvt
  tier_pdf: $_/generated/tier/pdf
  pdf_releases: $_/generated/releases
  plots: $_/generated/plots

precompile_pkg:
  - dspeed.processors
  - lgdo.compression
  - matplotlib
  - pygama
  - pygeomhpges
  - pygeomoptics
  - pygeomtools
  - reboost
  - remage
  - revertex
#
# runcmd:
#   remage: apptainer run --cleanenv /home/gipert/sw/apptainer/remage_latest.sif
#
# nersc:
#   dvs_ro: true
#   scratch: $SCRATCH/legend-simflow
