# reserved first-level fields:
#   - metadata

# label identifying the experimental configuration to be simulated. See
# https://github.com/legend-exp/legend-simflow-config/blob/main/README.md
# for a list of currently supported values.
experiment: l200cfg09

# simflow_rng_seed: 0

# runlist:
# - l200-p03-r000-phy
# - l200-p03-r001-phy
# - l200-p03-r002-phy
# - l200-p03-r005-phy
# - l200-p04-r000-phy
# - l200-p04-r001-phy

simlist: all

# list of tiers to build. Remove tiers you don't need to speed things up:
# - remove 'opt' (and 'fiber', 'pen' from paths.optical_maps below) if you
#   don't need liquid argon / SiPM optical simulation post-processing
make_tiers:
  - vtx
  - stp
  - opt
  - hit
  - evt
  - cvt

# legend_metadata_version: main

benchmark:
  enabled: false
  n_primaries:
    stp: 10_000

paths:
  generated: $_/generated
  l200data: <...>/public/prodenv/prod-blind/ref-v1.0.0
  benchmarks: $_/generated/benchmarks
  log: $_/generated/log

  metadata: $_/inputs
  config: $_/inputs/simprod/config
  optical_maps:
    fiber: $_/inputs/simprod/l200a-optical-map-fiber.lh5
    lar: $_/inputs/simprod/l200a-optical-map-lar.lh5
    pen: $_/inputs/simprod/l200a-optical-map-pen.lh5

  pars: $_/generated/pars
  macros: $_/generated/macros
  # geom: $_/generated/pars/geom
  # dtmaps: $_/generated/pars/hpge/dtmaps
  tier:
    vtx: $_/generated/tier/vtx
    stp: $_/generated/tier/stp
    opt: $_/generated/tier/opt
    hit: $_/generated/tier/hit
    evt: $_/generated/tier/evt
    cvt: $_/generated/tier/cvt
    pdf: $_/generated/tier/pdf
  pdf_releases: $_/generated/releases

precompile_pkg:
  - dspeed.processors
  - lgdo.compression
  - matplotlib
  - pygama
  - pygeomhpges
  - pygeomoptics
  - pygeomtools
  - reboost
  - remage
  - revertex
#
# runcmd:
#   remage: apptainer run --cleanenv /home/gipert/sw/apptainer/remage_latest.sif
#
# nersc:
#   dvs_ro: true
#   scratch: $SCRATCH/legend-simflow
