configfile: simflow-config.yaml
keep-going: true
rerun-incomplete: true
cores: all

# we can use conda environments on NERSC
software-deployment-method: conda

# I/O on scratch disk for performance
default-storage-provider: fs
local-storage-prefix: $SCRATCH/legend-simflow
shared-fs-usage:
  - persistence
  - software-deployment
  - sources
  - source-cache
